---
title: "Election Project"
author: "Jackson Callaghan"
date: "4/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(ggridges)
library(scales)
library(gridExtra)
library(viridis)
library(maps)
library(fiftystater)
```

```{r}
theme_set(theme_minimal())
```



```{r}
# read in age demographics
raw.byage <- read_excel(
  "CPS Turnout Rates.xlsx",
  sheet = "Age",
  range = "A2:R6"
)

# pivot to tidy shape
byage <- raw.byage %>% 
  pivot_longer(cols = 2:length(raw.byage), names_to = "year", values_to = "turnout")
colnames(byage)[1] = "age.group"
# change types and mutate new type column
byage$year <- as.numeric(byage$year)
byage <- byage %>% mutate(type = ifelse(year %in% seq(1986, 2020, 4), "Midterm", "Presidential"))
byage$type <- factor(byage$type, levels = c("Presidential", "Midterm"))
```

```{r}
ggplot(byage) +
  aes(
    x = as.factor(year), 
    y = turnout, 
    color = age.group, 
    group = age.group) +
  geom_line(size = 1) +
  scale_y_continuous(labels = scales::percent, limits = c(0, 1)) +
  labs(x = "Year", y = "Turnout", title = "Election Turnout", color = "Age Group") +
  theme_minimal() +
  scale_color_viridis(discrete = TRUE) +
  facet_wrap(~type, scales = "free_x") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r message=FALSE, warning=FALSE}
raw.alltime <- read_csv("U.S. VEP Turnout 1789-Present - Statistics.csv")
all.pres <- raw.alltime[, 1:2]
all.midt <- raw.alltime[, 3:4]
colnames(all.pres) <- c("year", "turnout")
colnames(all.midt) <- c("year", "turnout")

all.pres$type <- rep("Presidential", nrow(all.pres))
all.midt$type <- rep("Midterm", nrow(all.midt))

alltime <- full_join(all.pres, all.midt)
alltime$type <- factor(alltime$type, levels = c("Presidential", "Midterm"))
```

```{r}
ggplot(alltime) +
  aes(
    x = year, 
    y = turnout, 
    color = type, 
    group = type) +
  geom_line(size = 1) +
  ylim(0, 100) +
  labs(x = "Year", y = "Turnout", title = "Overall Election Turnout", color = "Election Type") +
  theme_minimal() +
  scale_color_viridis(discrete = TRUE) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
gen.turn <- read_excel(
  "1980-2014 November General Election.xlsx",
  skip = 1
)

gen.turn.2016 = read_excel(
  "2016 November General Election.xlsx",
  skip = 1
)

gen.turn <- gen.turn %>%
  select(-(2:3), -c(5, 7, 8, 11), -(12:17)) 

colnames(gen.turn) <- c("year", "region", "turnout", "ballots", "VEP")
gen.turn$region <- sapply(gen.turn$region, tolower)
gen.turn <- mutate(gen.turn, type = ifelse(year %in% seq(1980, 2020, 4), "Presidential", "Midterm"))

gen.turn.2016 <- gen.turn.2016 %>%
  select(-(2:3), -c(4, 6, 7, 10), -(11:17)) 

colnames(gen.turn.2016) <- c("region", "turnout", "ballots", "VEP")
gen.turn.2016$region <- sapply(gen.turn.2016$region, tolower)
gen.turn.2016$year <- rep(2016, nrow(gen.turn.2016))
gen.turn.2016$type <- rep("Presidential", nrow(gen.turn.2016))

gen.turn <- full_join(gen.turn, gen.turn.2016)

states.turnout <- gen.turn %>% filter(region != "united states")
total.turnout <- gen.turn %>% filter(region == "united states")

# head(gen.turn)
```

```{r}
states_map <- map_data("state")
merge <- states.turnout %>% 
  filter(year == 2012)

merge <- inner_join(states_map, merge, by = "region")
merge
```

```{r}
data("fifty_states")

states.turnout %>% 
            filter(year == 2016) %>% 
            ggplot(aes(map_id = region)) +
                geom_map(aes(fill = turnout), map = fifty_states, color = "white") +
                expand_limits(x = fifty_states$long, y = fifty_states$lat) +
                coord_map(projection = "albers", lat0=30, lat1=40) +
                labs(fill = "Turnout") +
                theme_void() +
                scale_fill_viridis(limits = c(0, 1)) +
                fifty_states_inset_boxes() +
                facet_wrap(~type)
```

```{r}
# read in age demographics
raw.byrace <- read_excel(
  "CPS Turnout Rates.xlsx",
  sheet = "Race and Ethnicity",
  range = "A2:R6"
)

# pivot to tidy shape
byrace <- raw.byrace %>% 
  pivot_longer(cols = 2:length(raw.byrace), names_to = "year", values_to = "turnout")
colnames(byrace)[1] = "group"
# change types and mutate new type column
byrace$year <- as.numeric(byrace$year)
byrace <- byrace %>% mutate(type = ifelse(year %in% seq(1986, 2020, 4), "Midterm", "Presidential"))
byrace$type <- factor(byrace$type, levels = c("Presidential", "Midterm"))
```

```{r}
ggplot(byrace) +
  aes(
    x = as.factor(year), 
    y = turnout, 
    color = group, 
    group = group) +
  geom_line(size = 1) +
  scale_y_continuous(labels = scales::percent, limits = c(0, 1)) +
  labs(x = "Year", y = "Turnout", title = "Election Turnout", color = "Age Group") +
  theme_minimal() +
  scale_color_viridis(discrete = TRUE) +
  facet_wrap(~type, scales = "free_x") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r}
# read in age demographics
raw.byedu <- read_excel(
  "CPS Turnout Rates.xlsx",
  sheet = "Education",
  range = "A2:R6"
)

# pivot to tidy shape
byedu <- raw.byedu %>% 
  pivot_longer(cols = 2:length(raw.byedu), names_to = "year", values_to = "turnout")
colnames(byedu)[1] = "edu_lvl"
# change types and mutate new type column
byedu$year <- as.numeric(byedu$year)
byedu <- byedu %>% mutate(type = ifelse(year %in% seq(1986, 2020, 4), "Midterm", "Presidential"))
byedu$type <- factor(byedu$type, levels = c("Presidential", "Midterm"))
byedu$edu_lvl <- factor(byedu$edu_lvl, levels = c("Less Than High School", "High School Grad", "Some College to College Grad", "Post-Graduate"))
```

```{r}
ggplot(byedu) +
  aes(
    x = as.factor(year), 
    y = turnout, 
    color = edu_lvl, 
    group = edu_lvl) +
  geom_line(size = 1) +
  scale_y_continuous(labels = scales::percent, limits = c(0, 1)) +
  labs(x = "Year", y = "Turnout", title = "Election Turnout", color = "Age Group") +
  theme_minimal() +
  scale_color_viridis(discrete = TRUE) +
  facet_wrap(~type, scales = "free_x") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

