---
title: "INFO248 Project"
author: "Jackson Callaghan & Hans Quiogue"
date: "4/29/2020"
output: pdf_document
---

```{r Libraries, message=FALSE, warning=FALSE, include=FALSE}
library(readxl)
library(tidyverse)
```

```{r 2018 voting data per state, message=FALSE, warning=FALSE}
state_2018 <- read_xlsx("state_2018.xlsx", skip = 5)

# Cleaning column names
colnames(state_2018) <- c("State", "Age", "Total Population", "Total Citizen Population",
                          "Total Registered", "Total Percent Registered", "Error (1)",
                          "Percent Registered (Citizen)", "Error (2)", "Total Voted",
                          "Total Percent Voted", "Error (3)", "Percent Voted (Citizen)",
                          "Error (4)")

# Fill NA spots in first column with corresponding state names
all_names <- c("US", state.name)
# Adds DC in list after Delware (9th element)
all_names <- append(all_names, "DC", 9)
# Represents current index num. of state list 'all_names'
cnt = 1

# Loop that replaces NA with correct state names
for(i in 1:nrow(state_2018)) {
  curr_state <- all_names[cnt]     
  state_2018[i,][1] <- curr_state 
  if(i %% 6 == 0) {
    cnt = cnt + 1  
  }
}

state_2018 <- na.omit(state_2018)
state_2018
```

```{r Graph examples, message=FALSE, warning=FALSE}
# Total number young people in US who voted and registered
total_young <- state_2018 %>%
  filter(Age == "18 to 24" & State == "US") %>% 
  select(Age, `Total Population`, `Total Voted`, `Total Registered`)

# Total number in US who voted and registered
total_pop <- state_2018 %>% 
  filter(Age == "Total" & State == "US") %>%
  select(Age, `Total Population`, `Total Voted`, `Total Registered`)

df <- rbind(total_pop, total_young)
df$Age <- as.factor(df$Age)

# Barplot showing how little young people vote compared to the rest of the population 
ggplot(df) +
  aes(Age, `Total Voted`) +
  geom_bar(stat = "identity")
```

```{r}
young_2018 <- read_xlsx("young_2018.xlsx", skip = 6)

# Cleaning column names
colnames(young_2018) <- c("Gender", "Education", "Total Population",
                          "Total Citizen Population", "Number (Registered)",
                          "Percent (Registered)", "Number (Not Registered)",
                          "Percent (Not Registered)", "Number (No Response Registration)",
                          "Percent (No Response Registration)", "Number (Voted)", 
                          "Percent (Voted)", "Number (Not Voted)", "Percent (Not Voted)", 
                          "Number (No Response Vote)", "Percent (No Response Vote)")

genders <- c("Both Sexes", "Male", "Female")

# Represents current index num. of genders list
cnt = 1

# Loop that replaces NA with correct genders names
for(i in 1:nrow(young_2018)) {
  cur_gender <- genders[cnt]     
  young_2018[i,][1] <- cur_gender
  if(i %% 7 == 0) {
    cnt = cnt + 1  
  }
}

young_2018 <- na.omit(young_2018)
young_2018
```

