---
title: "INFO248 Project"
author: "Jackson Callaghan & Hans Quiogue"
date: "4/29/2020"
output: pdf_document
---

```{r Libraries, message=FALSE, warning=FALSE, include=FALSE}
library(readxl)
library(tidyverse)
```

```{r 2018 voting data per state, message=FALSE, warning=FALSE}
state_2018 <- read_xlsx("state_2018.xlsx", skip = 5)

# Cleaning column names
colnames(state_2018) <- c("State", "Age", "Total Population", "Total Citizen Population",
                          "Total Registered", "Total Percent Registered", "Error (1)",
                          "Percent Registered (Citizen)", "Error (2)", "Total Voted",
                          "Total Percent Voted", "Error (3)", "Percent Voted (Citizen)",
                          "Error (4)")

# Fill NA spots in first column with corresponding state names
all_names <- c("US", state.name)
# Adds DC in list after Delware (9th element)
all_names <- append(all_names, "DC", 9)
# Represents current index num. of state list 'all_names'
cnt = 1

# Loop that replaces NA with correct state names
for(i in 1:nrow(state_2018)) {
  curr_state <- all_names[cnt]     
  state_2018[i,][1] <- curr_state 
  if(i %% 6 == 0) {
    cnt = cnt + 1  
  }
}

state_2018 <- na.omit(state_2018)
state_2018
```

```{r Graph examples, message=FALSE, warning=FALSE}
# Barplot showing how little young people vote compared to the rest of the population 
ggplot(state_2018) +
  aes(Age, `Total Voted`, fill = Age) +
  geom_col(stat = "identity")
```

```{r Young People and Education in 2018, message=FALSE, warning=FALSE}
educ_2018 <- read_xlsx("young_2018.xlsx", skip = 6)

# Cleaning column names: TODO: Make column names proper
colnames(educ_2018) <- c("Gender", "Education", "Total Population",
                          "Total Citizen Population", "Number (Registered)",  
                          "Percent (Registered)", "Number (Not Registered)",
                          "Percent (Not Registered)", "Number (No Response Registration)",
                          "Percent (No Response Registration)", "Number (Voted)", 
                          "Percent (Voted)", "Number (Not Voted)", "Percent (Not Voted)", 
                          "Number (No Response Vote)", "Percent (No Response Vote)",
                          "temp", "temp2")

genders <- c("Both Sexes", "Male", "Female")

# Represents current index num. of genders list
cnt = 1

# Loop that replaces NA with correct genders names
for(i in 1:nrow(educ_2018)) {
  cur_gender <- genders[cnt]     
  educ_2018[i,][1] <- cur_gender
  if(i %% 7 == 0) {
    cnt = cnt + 1  
  }
}

educ_2018 <- na.omit(educ_2018)
```

```{r message=FALSE, warning=FALSE}
# Will education level for 18-24 year olds affect vote?
educ_2018 %>% 
  filter(Gender == "Both Sexes" & Education != "Total") %>% 
  ggplot(aes(Education, as.numeric(`Total Population`), fill = Education)) +
  geom_bar(stat = "identity")

educ_2018 %>% 
  filter(Gender != "Both Sexes" & Education != "Total") %>% 
  ggplot(aes(Education, as.numeric(`Total Population`), fill = Education)) +
  geom_bar(stat = "identity") +
  facet_wrap(~Gender)

# TODO: Statistical test (Higher education level, more they will vote perhaps?)
# TODO: Perhaps get education data from earlier years to see if education has impacted young people voting when compared to today
```

```{r}
# Will gender for 18-24 year olds affect vote? 

educ_2018 %>% 
  filter(Gender != "Both Sexes" & Education != "Total") %>% 
  ggplot(aes(Gender, as.numeric(`Total Population`), fill = Gender)) +
  geom_col(stat = "identity")

# TODO: Statistical test? (From plots perhaps gender does not have a role in vote for 18-24 years)
```

